import React from 'react'
import { data } from './data'

export default function Edit(props) {
    console.log(props)

    return (
        <div>
            {data
            .filter(item => item.id === props.cardNumber)
            .map(item => 

            <div key={item.id} className="content">
                <form 
                onSubmit={(e) => {
                    e.preventDefault()
                    props.handleEditing()
                }}
                    
                className="firstNameInput">
                    <h3>Personal Info</h3>

                    <label> First Name 
                        <input type="text"
                         placeholder={item.name.first}
                         onChange={(e) => {
                            //  item.id - 1 will need us to create autogenerated id's for the new users
                            data[item.id - 1].name.first = e.target.value 
                            }}
                          /></label>

                    <label> Last Name 
                        <input type="text"
                         placeholder={item.name.last}
                         onChange={(e) => {
                            //  item.id - 1 will need us to create autogenerated id's for the new users
                            data[item.id - 1].name.last = e.target.value 
                            }}
                          /></label>
        
                        <label> City 
                            <input type='text'
                             placeholder={item.city}
                             onChange={(e) => {
                                //  item.id - 1 will need us to create autogenerated id's for the new users
                                data[item.id - 1].city = e.target.value 
                                }}
                              /></label>

                        <label> Country 
                            <input type='text'
                             placeholder={item.country}
                             onChange={(e) => {
                                //  item.id - 1 will need us to create autogenerated id's for the new users
                                data[item.id - 1].country = e.target.value 
                                }}
                              /></label>

                        <label> Job Title 
                            <input type='text'
                             placeholder={item.title}
                             onChange={(e) => {
                                //  item.id - 1 will need us to create autogenerated id's for the new users
                                data[item.id - 1].title = e.target.value 
                                }}
                              /></label>

                        <label> Employer 
                            <input type='text'
                             placeholder={item.employer}
                             onChange={(e) => {
                                //  item.id - 1 will need us to create autogenerated id's for the new users
                                data[item.id - 1].employer = e.target.value 
                                }}
                              /></label>

                    <br/>

                    <h3>Favorite Movies:</h3>

                    <label> Add Favorites Movies </label>
                    <ol>
                        <input type="text" placeholder={item.favoriteMovies[0]}
                        onChange={(e) => {
                            //  item.id - 1 will need us to create autogenerated id's for the new users
                            data[item.id - 1].favoriteMovies[0] = e.target.value 
                            }}
                        />
                        <input type="text" placeholder={item.favoriteMovies[1]}
                        onChange={(e) => {
                            //  item.id - 1 will need us to create autogenerated id's for the new users
                            data[item.id - 1].favoriteMovies[1] = e.target.value 
                            }}
                        />
                        <input type="text" placeholder={item.favoriteMovies[2]}
                        onChange={(e) => {
                            //  item.id - 1 will need us to create autogenerated id's for the new users
                            data[item.id - 1].favoriteMovies[2] = e.target.value 
                            }}
                        />
                    </ol>

                    <button type="submit" >Save</button>
                </form>
            </div>
            )}
        </div>
    )
}
